### ISSUE TITLE
Could not install on Termux

### ISSUE THREAD

**Issue by itokariuk** [python-poetry/install.python-poetry.org#107]
Could not install Poetry on Termux with the command `curl -sSL https://install.python-poetry.org | python3 -`.

Output:
![IMG_20230226_184112](https://user-images.githubusercontent.com/107887698/221423967-1c05a4d0-0393-45fd-8014-cbb1b398002d.jpg)

Log file:
https://pastebin.com/hUk4uWVF

How can i fix it?

**Comment by dimbleby** [comment]
Read the error message?

```
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust
 
          Python: 3.11.2
          platform: Linux-4.4.192-perf-g6859189-aarch64-with-libc
          pip: n/a
          setuptools: 67.4.0
          setuptools_rust: 1.5.2
          rustc: 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball)
          =============================DEBUG ASSISTANCE=============================```
```
NB this is really not to do with poetry

**Comment by itokariuk** [comment]
> Read the error message?
> 
> ```
>           =============================DEBUG ASSISTANCE=============================
>           If you are seeing a compilation error please try the following steps to
>           successfully install cryptography:
>           1) Upgrade to the latest pip and try again. This will fix errors for most
>              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
>           2) Read https://cryptography.io/en/latest/installation/ for specific
>              instructions for your platform.
>           3) Check our frequently asked questions for more information:
>              https://cryptography.io/en/latest/faq/
>           4) Ensure you have a recent Rust toolchain installed:
>              https://cryptography.io/en/latest/installation/#rust
>  
>           Python: 3.11.2
>           platform: Linux-4.4.192-perf-g6859189-aarch64-with-libc
>           pip: n/a
>           setuptools: 67.4.0
>           setuptools_rust: 1.5.2
>           rustc: 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball)
>           =============================DEBUG ASSISTANCE=============================```
> ```
> NB this is really not to do with poetry

Yes, I read it, but I still don't understand what the problem is.

**Comment by dimbleby** [comment]
you'll need to take that up with `cryptography`.

this really is nothing to do with poetry, as you can likely verify just by running `pip install cryptography`

**Comment by dimbleby** [comment]
which shows that this issue is not with poetry.  Please close it down and try at the cryptography repository.  (Check for duplicates first!)

**Comment by itokariuk** [comment]
> which shows that this issue is not with poetry.  Please close it down and try at the cryptography repository.  (Check for duplicates first!)

Okay, thank you
