### ISSUE TITLE
installing poetry fails with a stacktrace (using python 3.8 as the script runner)

### ISSUE THREAD

**Issue by georgettica** [python-poetry/install.python-poetry.org#48]
- **Poetry version**: 1.2.1 (but not found by poetry --version)
- **Python version**:  Python 3.8.14 (but not found by a poetry command aswell)
- **OS version and name**:  ubuntu 22.04 (containerized)
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

The issue I am having is regarding the https://install.python-poetry.org command.

as explained [here](https://github.com/georgettica/poetry-installation-failure), I provided a container and the command I ran and the outputs I got.

I am having other issues I am solving internally that might be related to the new version so solving this might help me reduce some variance I am having in my testing

**Comment by neersighted** [comment]
Thanks for the detailed report! In the future (and for anyone else reading), for something like this a simple recap of the Dockerfile and install command would be sufficient.

What's happening here is the latest `poetry-core` fixed a bug where it didn't report invalid constraints (and instead cast them) to the any constraint (`*`). Poetry itself contained an invalid constraint in the git revision you are attempting to install. The latest core cannot be install that revision after the fix, as a result.

If you truly need to pin that revision, you'll need to create a new branch that cherry-picks the constraint fix onto the revision you originally tried to install. However, simply installing release version 1.2.1 (`--version 1.2.1`) is much safer and will work just fine with your setup.

**Comment by georgettica** [comment]
@neersighted , I wanted to note I tried to install [this commit](https://github.com/python-poetry/poetry/commit/d5c22c2641c415d5fea7cb321f3df7a0a873753b).
not sure on what release it falls but wanted to clarify this for you and future readers

**Comment by neersighted** [comment]
Worth noting that that is not 1.2.1 and a pretty old commit that still contains the bad constraint:

https://github.com/python-poetry/poetry/blob/d5c22c2641c415d5fea7cb321f3df7a0a873753b/pyproject.toml#L68

In fact, that commit is somewhere between 1.2 betas (and not even a RC) and is full of a lot of regressions and missing features relative to the released version (so the docs won't be very useful).
