### ISSUE TITLE
install-poetry.py creates a symbolic link to a non existant path

### ISSUE THREAD

**Issue by ronlut** [python-poetry/install.python-poetry.org#59]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: python-3.8.11-alpine (docker)
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Using the following dockerfile, poetry isn't installed correctly.
After running a shell in this container, I get the following situation (notice the target of the symlink is broken)
![image](https://user-images.githubusercontent.com/3050627/125202134-e45b2c80-e27a-11eb-8152-ef479790dc71.png)
```
/ # ls -an /etc/poetry/venv/bin/poetry
ls: /etc/poetry/venv/bin/poetry: No such file or directory
```

And poetry is unusable.
This doesn't happen with get-poetry.py

Dockerfile to reproduce:
```
ARG PYTHON_VERSION=3.8.11
ARG POETRY_VERSION=1.1.7

FROM python:$PYTHON_VERSION-alpine as base

ENV PIP_DISABLE_PIP_VERSION_CHECK=on \
    POETRY_VERSION=$POETRY_VERSION \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    POETRY_HOME=/opt/poetry \
    PATH="$POETRY_HOME/bin:$PATH"

RUN apk add --no-cache curl && \
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
```

**Comment by mg-christian-axelsson** [comment]
I ran into this today. My issue stemmed from having environment variable `PIP_TARGET` set to a custom Python path. This worked with the old `get-poetry.py` installer but not with the new installer.

**Comment by neersighted** [comment]
The old installer did not use pip -- we could start running pip in isolated mode to avoid that with this installer, but users with index/credential settings in their pip config will find they are not respected.

Closing as this is solved in the general case.
