### ISSUE TITLE
install-poetry.py installs to the wrong location

### ISSUE THREAD

**Issue by cjw296** [python-poetry/install.python-poetry.org#60]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.6
- **Poetry version**:  1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

[These docs](https://python-poetry.org/docs/master/#installation) say poetry should be installed to `$HOME/.local/bin`, but:

```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/chris/Library/Python/3.7/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.11): Done

Poetry (1.1.11) is installed now. Great!

To get started you need Poetry's bin directory (/Users/chris/Library/Python/3.7/bin) in your `PATH`
environment variable.

Add `export PATH="/Users/chris/Library/Python/3.7/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/Users/chris/Library/Python/3.7/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`


```

**Comment by neersighted** [comment]
This was fixed in https://github.com/python-poetry/install.python-poetry.org/commit/ac6fb50a38185c19acc5adef2c0e0fc815c26abb
