### ISSUE TITLE
bootstrap: remove dependency on system provided pip

### ISSUE THREAD

**Issue by abn** [python-poetry/install.python-poetry.org#61]
We should do a check for pip, as pip is not always present. If it's not present we have one of two options.

1. Automatically execute `python -m ensurepip`. 
2. Error out, instructing user to install pip and hint at 1, since they may want to use distro specific installation. 

Alternatively, `virtualenv` wheel should be usable without installation I think. That would make a cleaner approach.
1. Download latest wheel.
2. Insert wheel to site.
3. Execute required commands.

_Originally posted by @abn in https://github.com/python-poetry/poetry/pull/3706#r598254393_

**Comment by neersighted** [comment]
This is now implemented.
