### ISSUE TITLE
poetry install fails using Windows Powershell: unknown url type: https

### ISSUE THREAD

**Issue by dataspun** [python-poetry/install.python-poetry.org#75]
- **Poetry version**: n/a poetry install fails
- **Python version**: miniconda python 3.9.12
- **OS version and name**: Windows 11
- **pyproject.toml**: n/a

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Trying to install poetry using the recommended Powershell method:

`(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -`

Here is the output:

```
Retrieving Poetry metadata
Traceback (most recent call last):
  File "<stdin>", line 940, in <module>
  File "<stdin>", line 919, in main
  File "<stdin>", line 516, in run
  File "<stdin>", line 775, in get_version
  File "<stdin>", line 836, in _get
  File "C:\Users\xxx\miniconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\xxx\miniconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\xxx\miniconda3\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\xxx\miniconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\xxx\miniconda3\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

**Comment by neersighted** [comment]
Looks like your Python (miniconda) does not provide a fully featured urllib3. Please use a standard, Python.org Python if you want a fully featured stdlib that includes https support.

**Comment by dataspun** [comment]
@neersighted thanks but given that miniconda and poetry don't play nicely together seems like a larger issue deserving mention in poetry's [installation docs](https://python-poetry.org/docs/#system-requirements). 

also, installing poetry with a standard, Python.org Python is not the solution either: [different issue](https://github.com/python-poetry/poetry/issues/6872).

**Comment by neersighted** [comment]
miniconda being deficient in the built modules (e.g. not building against OpenSSL) is not Poetry's fault in my opinion. If you try to install Poetry with a distribution that does not include the standard amenities, that's your decision.

Regarding the issue you opened, that is a bug if we can reproduce it/it's not a local configuration error. You have not provided nearly enough detail to debug the issue however -- please look at the issue template and provide the debug info requested.

**Comment by neersighted** [comment]
In fact, it looks like this is a local config issue common to Anaconda, especially on Windows: https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#ssl-connection-errors

**Comment by dataspun** [comment]
@neersighted good info thanks, but saying it's not poetry's fault is missing the point. 

I still think it's worth poetry improving its own documentation, at the very least.

**Comment by neersighted** [comment]
I'm not sure links to anaconda-specific documentation for an issue that most users will never encounter is useful, is all. We can certainly have some sort of 'common install issues' section where hints about missing SSL support are added, but adding a callout for a very niche Anaconda-specific issue in the section you have suggested is adding meaningless noise in my opinion.

**Comment by dataspun** [comment]
@neersighted this issue seems more than _niche_.

Granted, it's Anaconda's issue to solve but it seems appropriate for Poetry to flag it for its own audience.  Adding a Troubleshooting section to Poetry's documentation would be very helpful.
