### ISSUE TITLE
Installation error using python 3.9.15

### ISSUE THREAD

**Issue by sameervk** [python-poetry/install.python-poetry.org#91]
Running "$ curl -sSL https://install.python-poetry.org | python3 -" with python 3.9.15 is resulting in the error in the attached image

![image](https://user-images.githubusercontent.com/16178000/206528139-b6413294-3f52-457e-9c70-4b25ec77a01a.png)

Changed the python version to 3.10.8, and it works fine.

**Comment by neersighted** [comment]
This is an issue with your local Python, which is unable to make HTTPS requests (likely due to a missing OpenSSL module).
