### ISSUE TITLE
curl install error - An internal error occurred with Vercel.

### ISSUE THREAD

**Issue by mikeumus** [python-poetry/install.python-poetry.org#92]
**Error while attempting to install on MacOS:**
```
> $ curl -sSL https://install.python-poetry.org | python3 -                                  ⬡ 18.12.1 

  File "<stdin>", line 1
    An internal error occurred with Vercel.
       ^^^^^^^^
SyntaxError: invalid syntax
```

**curl version**
```
> $ curl --version                                                                           ⬡ 18.12.1 
curl 7.84.0 (x86_64-apple-darwin22.0) libcurl/7.84.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
Release-Date: 2022-06-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets`
```

**python3 version**
```
> $ python3 --version                                                                        ⬡ 18.12.1 
Python 3.10.8
```
_ _ _

**MacOS Version 13.0.1 (22A400)
Chip Apple M1 Max**

_ _ _

🙇🏻‍♂️ Thanks in advance for any insight and hope to this helping others who may be hitting this little hurtle. 
☃️ Happy Holidays!

**Comment by mikeumus** [comment]
Work-around: 
`brew install poetry`
https://formulae.brew.sh/formula/poetry#default
😃

**Comment by neersighted** [comment]
I've transferred your issue to the correct repository, as the installer is developed separately.

> `brew install poetry`

This may work for you, but please be aware we provide no support for distro-provided/repackaged Poetry, and all bug reports must be with Poetry as provided by the upstream project. Downstream modifications frequently cause problems for users and we cannot reasonably account for them upstream.

---

Please try `curl https://install.python-poetry.org` several times and see if you get the Python script back -- I have hit it from machines around the world and the CDN appears to be delivering the correct content.

If you're still having problems with Vercel's CDN, `curl -sSL https://raw.githubusercontent.com/python-poetry/install.python-poetry.org/main/install-poetry.py | python3` is a better workaround (using the version of the script in this repo).

**Comment by mikeumus** [comment]
Check to see if you already installed poetry from Brew 😅 
```
> $ brew install poetry                                                                      ⬡ 18.12.1 
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
clitest          clusterawsadm    dotnet@6         gobackup         php@8.1          snakefmt

You have 1 outdated formula installed.
You can upgrade it with brew upgrade
or list it with brew outdated.

Warning: poetry 1.2.2_1 is already installed and up-to-date.
To reinstall 1.2.2_1, run:
  brew reinstall poetry
```


https://formulae.brew.sh/formula/poetry#default 😃
