### ISSUE TITLE
Poetry installation fails: failure in installing cryptography package on Raspberry Pi 4

### ISSUE THREAD

**Issue by alonbudker-vayyar** [python-poetry/install.python-poetry.org#96]
# Overview
Hey!
I'm trying to install poetry on a Raspberry Pi 4 system, and the installation fails.

The command I run is:
`curl -sSL https://install.python-poetry.org | python3 - --version=1.2.2`
and the error is:
```
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
```
The full log is attached below, and in it we can see that the underlying issue is that the installation was attempted from source, and that the rust compiler `rustc` is missing.

It looks like:

- The `cryptography` package is a requirement for poetry
- Pip tries to find a wheel for it in [pi-wheels](https://www.piwheels.org/project/cryptography/) but fails for some reason...
- The installation reverts to an installation from source
- To install it from source, the rust compiler is required and is missing

In the past (Last time I tried was approximately 1 month ago) the installation was successful.

# Details
## System Information
```
Raspberry Pi 4, running the OS: raspios_oldstable_armhf-2022-01-28
Python version: 3.9.2
Poetry version (to be installed): 1.2.2
System overview (output of uname -a): Linux <hostname> 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
```
Note that the processor is an arm processor.
OS can be found [here](https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-01-28/).

## Workaround
To work around the issue, I've copied the installation script from `https://install.python-poetry.org` and added the following:
```
OLD:
env.pip("install", specification)
---
NEW:
env.pip("install", specification, "--only-binary", "cryptography")
```

This forces pip to look for binaries instead of installing from source, and this solves the issue: poetry is installed successfully after I invoke the _new_ script.

## Poetry Installer Log
[poetry-installer-error-a5j_8p64.log](https://github.com/python-poetry/install.python-poetry.org/files/10308763/poetry-installer-error-a5j_8p64.log)

# Thoughts / Worries
Currently I can use the workaround to install poetry on my systems, but I don't want to depend on a divergent installation script from the one in this repository.

I couldn't figure out if the issue is something to do specifically with the `cryptography` package for the python version and processor version I'm using, and whether this issue is interesting to the maintainers of Poetry :)

Please let me know if this is interesting to look into, and if additional information is needed.

**Comment by alonbudker-vayyar** [comment]
I've opened an issue in the poetry installation script repo: https://github.com/python-poetry/install.python-poetry.org/issues/96

**Comment by finswimmer** [comment]
Hey,

there is no wheel file for your architecture, this is why it must be build from the `sdist` file. For doing this `Rust` is required as you can see in the log:

> error: can't find Rust compiler

You must install Rust to solve this problem. See also: https://cryptography.io/en/latest/installation/#rust

fin swimmer
